# Generated by Django 5.0 on 2024-01-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
