# Generated by Django 5.0 on 2024-01-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_description_alter_listings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
